### ISSUE TITLE
Instructions to convert videos to images are not working

### ISSUE THREAD

**Issue by b2m** [BioroboticsLab/bb_analysis#2]
The instructions to use bb_analysis (system 2) are documented in the [README](https://github.com/BioroboticsLab/bb_analysis/blob/master/system2/README.md).

The step "converting video files to images" is currently not working, because the given code snippet `ffmpeg -i video.mkv $filename%03d.jpg` produces not the expected results.

There are duplicate images: 001.jpg = 002.jpg and 003.jpg = 004.jpg.

The cause of this problem is unrelated to bb_analysis and might be a problem with either _ffmpeg_ or the generation of the video files. But actually it only seems to affect the bb_analysis project.

Maybe @hmoenck knows more about this?

**Comment by hmoenck** [comment]
This issue is known to exist, but little is known about it yet. Note that it is not evident, that the snippet doesn't work, implying it produces wrong output on correct input.
Does this occur in 2014/15 data only or also in 2016? 
If it occurs in all of them, can you also try unmuxed video from 2016? (To be found on Cray, $WORK2\Honeybees...)
I'm trying to figure out: Is it an encoding issue of ffmpeg, a muxing issue or a decoding issue?

**Comment by nebw** [comment]
According to @daign, it works just fine if you convert it to an mp4 file prior to extracting the images. Therefore, it may be a muxing issue.

**Comment by hmoenck** [comment]
More like a demuxing issue or demuxing wrongly muxed data. Whatever.
Maybe try setting -vsync 0
https://trac.ffmpeg.org/ticket/3817

**Comment by b2m** [comment]
When testing with a video from 2015 and additional parameter `-vsync 0` I only get 3 images (no duplicates), the following warning:

> [swscaler @ 0x1117e80] deprecated pixel format used, make sure you did set range correctly

and the following error:

> [mjpeg @ 0x110f2c0] Invalid pts (3) <= last (4) 01.66 bitrate=N/A  
> Video encoding failed
> Conversion failed!

**Comment by b2m** [comment]
This is the current workaround I am using (for reference): delete the duplicate images and rename the rest.

``` bash
ffmpeg -i video.mkv $filename%03d.jpg
rm 001.jpg 003.jpg
counter=1
for i in *.jpg; do
    new=$(printf "%03d.jpg" "$counter");
    mv -i -- "$i" "$new";
   let counter=counter+1;
done
```

**Comment by hmoenck** [comment]
That doesn't seem to be a satisfying long term solution.
The problem does not appear in 2016 data. Tested on:
`Cam_0_2016-08-06T17:12:31.569607Z--2016-08-06T17:18:11.415397Z.mkv`
2014 and 2015 are most likely both affected, as the encoding schemes were identical.
However, there are exactly 1024 frames in the tested video:
`/mnt/storage/hauke/HDSamples/Cam_3_20150828142945_847388_TO_Cam_3_20150828143526_863893.mkv`
as revealed by extracting the HEVC frames individually:
`ffmpeg\bin>ffmpeg.exe -i video.mkv -c:v copy test\f%04d.png`
(Note that this will not yield real png image files but single HEVC frames. These could be converted to regular images (jpg/png))
I guess ffmpeg get's confused about the framerate and/or timestamps. However, this is a strange behaviour and I'm not quite sure why, as the videos have been muxed as hevc/mkv explicitly setting TS and FPS.
Consulting the [Docs](https://ffmpeg.org/ffmpeg.html), there seems a way of helping out here:

> -r[:stream_specifier] fps (input/output,per-stream)
>     Set frame rate (Hz value, fraction or abbreviation).
>     As an input option, ignore any timestamps stored in the file and instead generate timestamps assuming constant frame rate fps. This is not the same as the -framerate option used for some input formats like image2 or v4l2 (it used to be the same in older versions of FFmpeg). If in doubt use -framerate instead of the input option -r.
>     As an output option, duplicate or drop input frames to achieve constant output frame rate fps.

This does in fact deliver the 1024 distinct frames:
`ffmpeg.exe -c:v hevc -r 3 -i test.mkv -f image2 test\f%04d.png`
(use png for lossless encoding) @b2m @nebw Can you confirm this?
I also tried the workaround of mkv->mp4->jpg as suggested by @nebw , but it did not work. Can you give any details about what you did there so we may figure out why it is fixing the issue?

Tested using:
`ffmpeg version N-79585-g268b5ae Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-av
isynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enab
le-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --
enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-lib
modplug --enable-libmfx --enable-libmp3lame --enable-libopencore-amrnb --enable-
libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enabl
e-libschroedinger --enable-libsnappy --enable-libsoxr --enable-libspeex --enable
-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --ena
ble-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx
264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable
-lzma --enable-decklink --enable-zlib
  libavutil      55. 22.101 / 55. 22.101
  libavcodec     57. 38.100 / 57. 38.100
  libavformat    57. 34.103 / 57. 34.103
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 44.100 /  6. 44.100
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
  (Build from Zeranoe)`

**Comment by b2m** [comment]
**Works for me.** ~~So we need an additional converter to generated jpgs for the GUI or should we modify the GUI to be able to show the HEVC Frames as the background image for Truth Tracking?~~

**Comment by hmoenck** [comment]
Hm? Why?
`ffmpeg.exe -c:v hevc -r 3 -i test.mkv -f image2 test\f%04d.png`
yields valid PNG files (or jpg). Only 
`ffmpeg.exe -i video.mkv -c:v copy test\f%04d.png`
does not. So no converter needed. The sample and reasoning might have been confusing, sorry.

**Comment by hmoenck** [comment]
Hm? Why?
`ffmpeg.exe -c:v hevc -r 3 -i test.mkv -f image2 test\f%04d.png`
yields valid PNG files (or jpg). Only 
`ffmpeg.exe -i video.mkv -c:v copy test\f%04d.png`
does not. So no converter needed. The sample and reasoning might have been confusing, sorry.
